import type { ImagePickerAsset } from "expo-image-picker";
import type { CommunityPostResponse, CommunityPostUpdateRequest } from "../types/community";

export const IMAGE_DESCRIPTION_MAX_LENGTH = 240;
export const COMMUNITY_POST_MAX_LENGTH = 600;
export interface CommunityPostDraft {
  body: string;
  imageDescription: string;
  existingMedia: string | null;
  image: ImagePickerAsset | null;
  removeImage: boolean;
}
export const emptyPostDraft: CommunityPostDraft = {
  body: "", imageDescription: "", existingMedia: null, image: null, removeImage: false,
};
export function draftFromPost(post: CommunityPostResponse): CommunityPostDraft {
  return { ...emptyPostDraft, body: post.body, existingMedia: post.mediaData ?? null,
    imageDescription: post.mediaData ? post.imageDescription ?? "" : "" };
}
export function replaceDraftImage(draft: CommunityPostDraft, image: ImagePickerAsset): CommunityPostDraft {
  return { ...draft, image, removeImage: false, imageDescription: "" };
}
export function removeDraftImage(draft: CommunityPostDraft): CommunityPostDraft {
  return { ...draft, image: null, removeImage: Boolean(draft.existingMedia), imageDescription: "" };
}
export function draftHasImage(draft: CommunityPostDraft): boolean {
  return Boolean(draft.image || (draft.existingMedia && !draft.removeImage));
}
export function validatePostDraft(draft: CommunityPostDraft): string | null {
  if (!draft.body.trim()) return "Escreva algo antes de publicar.";
  if (draft.imageDescription.trim().length > IMAGE_DESCRIPTION_MAX_LENGTH) return "A descrição deve ter até 240 caracteres.";
  if (!draftHasImage(draft) && draft.imageDescription.trim()) return "A descrição exige uma imagem.";
  return null;
}
export function draftTextUpdate(draft: CommunityPostDraft): CommunityPostUpdateRequest {
  return { body: draft.body.trim(), imageDescription: draftHasImage(draft) ? draft.imageDescription.trim() || null : null };
}
/** Boundary is generated by fetch, never set Content-Type manually. */
export function createCommunityPostFormData(draft: CommunityPostDraft): FormData {
  const data = new FormData();
  data.append("body", draft.body.trim());
  data.append("imageDescription", draftHasImage(draft) ? draft.imageDescription.trim() : "");
  if (draft.removeImage) data.append("removeImage", "true");
  if (draft.image) {
    const asset = draft.image;
    const fileName = asset.fileName ?? `community-post-${Date.now()}.jpg`;
    const file = (asset as ImagePickerAsset & { file?: File }).file;
    data.append("image", file ?? ({ uri: asset.uri, name: fileName, type: asset.mimeType ?? "image/jpeg" } as unknown as Blob), ...(file ? [fileName] as [string] : []));
  }
  return data;
}
